hknweb/tutoring/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

hknweb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'accounts/', include([
            path('profile/', views.account_settings),
            path('settings/', views.account_settings),
            path('login/', auth_views.LoginView.as_view(template_name='admin/login.html')),
            path('logout/', auth_views.LogoutView.as_view()),
        ]),
    ),
    path('events/', include('hknweb.events.urls')),
    path('tutoring/', include('hknweb.tutoring.urls')),
]

hknweb/tutoring/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)


class Slot(models.Model):
    MON = 1
    TUE = 2
    WED = 3
    THU = 4
    FRI = 5
    DAY_CHOICES = [
        (MON, 'Mon'),
        (TUE, 'Tue'),
        (WED, 'Wed'),
        (THU, 'Thu'),
        (FRI, 'Fri'),
    ]

    CORY = 0
    SODA = 1
    ROOM_CHOICES = [
        (CORY, 'Cory'),
        (SODA, 'Soda'),
    ]

    HOUR_CHOICES = [
        (11, '11am'),
        (12, '12pm'),
        (13, '1pm'),
        (14, '2pm'),
        (15, '3pm'),
        (16, '4pm'),
    ]

    id = models.AutoField(primary_key=True)
    hour = models.IntegerField(choices=HOUR_CHOICES)
    day = models.IntegerField(choices=DAY_CHOICES)
    room = models.IntegerField(choices=ROOM_CHOICES)

    @staticmethod
    def time(hour):
        if hour < 12:
            return '{}am'.format(hour)
        else:
            return '{}pm'.format(hour)

    def start_time(self):
        return self.time(self.hour)

    def end_time(self):
        return self.time(self.hour + 1)


class Tutor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    slots = models.ManyToManyField(Slot)
    courses = models.ManyToManyField(Course)

hknweb/tutoring/views.py
from django.shortcuts import render

from .models import Slot


def index(request):
    days = [name for _, name in Slot.DAY_CHOICES]
    hours = Slot.HOUR_CHOICES
    cory_slots = {hour: Slot.objects.filter(room=Slot.CORY, hour=hour).order_by('day') for hour, _ in hours}
    soda_slots = {hour: Slot.objects.filter(room=Slot.SODA, hour=hour).order_by('day') for hour, _ in hours}
    context = {
        'days': days,
        'hours': hours,
        'offices': [
            {
                'room': '290 Cory',
                'slots': cory_slots,
            },
            {
                'room': '345 Soda',
                'slots': soda_slots,
            },
        ],
    }
    return render(request, 'tutoring/index.html', context)

hknweb/tutoring/templates/tutoring/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Tutoring{% endblock %}

{% block content %}
<style>
td {
    height: auto;
    text-align: center;
    padding: 15px;
    border-bottom: 1px solid #ddd;
}

.slider-container {
    padding: 10px 15px;
}

/* Tooltip text */
.tooltip .tooltiptext {
    visibility: hidden;
    width: 120px;
    background-color: black;
    color: #fff;
    text-align: center;
    padding: 5px 0;
    border-radius: 6px;
    width: 120px;
    bottom: 100%;
    left: 50%;
    margin-left: -60px; /* Use half of the width (120/2 = 60), to center the tooltip */

    /* Position the tooltip text - see examples below! */
    position: absolute;
    z-index: 1;
}

li {
    padding-bottom: 5px;
}
/* Show the tooltip text when you mouse over the tooltip container */
.tooltip:hover .tooltiptext {
    visibility: visible;
}

</style>

<div class="center measure-narrow measure-wide-m measure-very-wide-l pv4">
    <h1 class="font-title f3 f2-ns tc">Tutoring Schedule</h1>
    {% for office in offices %}
    <h2 class="font-title f4 f3-ns tc pb2 bb b--light-gray">{{office.room}}</h2>
    <table class="center font-body overflow-auto">
        <!-- Header row -->
        <tr>
            <th class="w3 pv2 bb b--light-gray">Hours</th>
            {% for day in days %}
            <th class="w4 pv2 bb b--light-gray">{{ day }}</th>
            {% endfor %}
        </tr>
        {% for hour, hour_pretty in hours %}
        <tr>
            <td class="pv2 w3 bb b--near-white"> {{hour_pretty}} </td>
            {% for slot in office.slots.hour %}
            <td class="pv2 w ba b--near-white">
                <ul class="list">
                    {% for tutor in slot.tutor_set.all %}
                    <li class="relative dib">{{tutor.name}}
                        <span class="tooltiptext">
                        {% for course in tutor.courses.all %}
                        {{course.name}}
                        {% endfor %}
                        </span>
                    </li>
                {% endfor %}
                </ul>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    {% endfor %}
</div>

{% endblock %}